# Sovereign 4.0 Voice Assistant - Production Configuration
# Environment: production
# This file contains production-specific overrides

# Environment and Metadata
environment: production
version: "4.0.0"
name: "Sovereign Voice Assistant"
description: "Advanced AI voice assistant with multi-modal capabilities"

# Feature Flags for Production
features:
  offline_mode: false
  memory_enabled: true
  screen_monitoring: true
  code_agent: true
  performance_monitoring: true
  voice_interruption: false
  emotion_detection: false
  multi_language: false

# API Configuration for Production
api:
  # Stricter validation in production
  validate_keys_on_startup: true
  timeout: 30.0
  max_retries: 3

# Audio System Configuration
audio:
  # Production-optimized audio settings
  vad_enabled: true
  silence_threshold: 0.001
  silence_duration: 1.0
  min_audio_length: 0.3
  max_audio_length: 30.0
  
  # Disable audio processing that might cause issues
  noise_reduction: false
  echo_cancellation: false
  automatic_gain_control: false

# Speech-to-Text Configuration
stt:
  # Production STT settings
  primary_provider: "openai"
  primary_model: "whisper-1"
  primary_language: "en"
  
  # Fallback for reliability
  fallback_provider: "whisper-cpp"
  fallback_model: "tiny.en"
  
  # Stricter timeouts for production
  timeout: 15.0
  temperature: 0.0
  max_retries: 3

# Text-to-Speech Configuration
tts:
  # Production TTS settings
  primary_provider: "openai"
  primary_model: "tts-1"
  primary_voice: "alloy"
  primary_speed: 1.0
  
  # Fallback for reliability
  fallback_provider: "piper"
  fallback_voice: "en_US-lessac-medium"
  
  # Production timeouts
  timeout: 20.0
  response_format: "mp3"
  max_retries: 3
  
  # Standard quality for production
  quality: "standard"
  enable_ssml: false

# Language Model Configuration
llm:
  # Production-optimized models
  fast:
    provider: "openrouter"
    model: "openai/gpt-4o-mini"
    max_tokens: 500
    temperature: 0.7
    timeout: 10.0
    cost_per_1k_tokens: 0.0002
    max_requests_per_minute: 1000
    context_window: 128000
  
  deep:
    provider: "openrouter"
    model: "openai/gpt-4o"
    max_tokens: 2000
    temperature: 0.7
    timeout: 45.0
    cost_per_1k_tokens: 0.005
    max_requests_per_minute: 500
    context_window: 128000
  
  local:
    provider: "llama-cpp"
    model: "gemma-2b-it-q4_0.gguf"
    max_tokens: 500
    temperature: 0.7
    timeout: 15.0
    cost_per_1k_tokens: 0.0
    max_requests_per_minute: 1000
    context_window: 2048
  
  # Robust fallback chain
  enable_fallback: true
  fallback_chain: ["fast", "deep", "local"]
  max_fallback_attempts: 3

# Memory System Configuration
memory:
  # Production memory settings
  provider: "chroma"
  persist_directory: "/var/lib/sovereign/data/chroma"
  collection_name_conversations: "sovereign_conversations"
  collection_name_screen: "sovereign_screen"
  
  # Production embeddings
  embedding_provider: "openai"
  embedding_model: "text-embedding-3-small"
  embedding_batch_size: 100
  
  # Production retrieval
  retrieval_k: 5
  similarity_threshold: 0.7
  max_context_length: 8000
  
  # Production memory management
  max_conversations_per_session: 100
  cleanup_interval_hours: 12
  enable_memory_compression: true

# Screen Monitoring Configuration
screen:
  enabled: true
  screenshot_interval: 5.0  # Less frequent in production
  
  # Production OCR settings
  ocr_provider: "tesseract"
  ocr_language: "eng"
  ocr_config: "--psm 6"
  tesseract_path: null
  
  # Production image preprocessing
  resize_factor: 0.8  # Smaller for performance
  contrast_enhancement: true
  noise_reduction: true
  
  # Production performance
  max_screen_history: 30
  enable_ocr_cache: true

# Code Agent Configuration
code_agent:
  enabled: true
  provider: "kimi"
  model: "kimi-k2"
  
  # Production trigger patterns
  trigger_patterns:
    - "#code"
    - "code:"
    - "programming"
    - "write code"
    - "debug"
    - "fix bug"
  
  # Production model settings
  max_tokens: 4000
  temperature: 0.1
  timeout: 90.0  # Longer timeout for production
  
  # Production context settings
  max_context_files: 10
  max_context_size: 50000

# Security Configuration
security:
  # Strict security for production
  validate_api_keys: true
  mask_keys_in_logs: true
  
  # Production encryption
  encrypt_memory: true
  encryption_key_file: "/etc/sovereign/encryption.key"
  
  # Production network security
  require_https: true
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
    - "0.0.0.0"
  
  # Production rate limiting
  enable_rate_limiting: true
  max_requests_per_minute: 60
  
  # Production logging security
  log_user_input: false  # Privacy in production
  log_assistant_responses: false  # Privacy in production
  sanitize_logs: true

# Performance Monitoring Configuration
monitoring:
  enabled: true
  log_level: "WARNING"  # Less verbose in production
  log_file: "/var/log/sovereign/sovereign.log"
  
  # Production metrics
  metrics_enabled: true
  metrics_port: 8080
  
  # Production health checks
  health_check_interval: 15.0
  health_check_timeout: 10.0
  
  # Production performance tracking
  track_latency: true
  track_memory_usage: true
  track_cpu_usage: true
  
  # Production error tracking
  error_reporting: true
  max_error_backlog: 50

# Development Configuration
development:
  debug_mode: false
  test_mode: false
  mock_apis: false
  
  # No hot reload in production
  enable_hot_reload: false
  hot_reload_paths: []
  
  # No development shortcuts
  skip_audio_init: false
  use_test_data: false
  bypass_api_validation: false 