# Sovereign 4.0 Voice Assistant - Offline Configuration
# Environment: offline
# This file contains offline-specific overrides

# Environment and Metadata
environment: offline
version: "4.0.0"
name: "Sovereign Voice Assistant"
description: "Advanced AI voice assistant with multi-modal capabilities (Offline Mode)"

# Feature Flags for Offline Mode
features:
  offline_mode: true
  memory_enabled: true
  screen_monitoring: true
  code_agent: false  # Disabled - requires internet
  performance_monitoring: true
  voice_interruption: false
  emotion_detection: false
  multi_language: false

# API Configuration for Offline Mode
api:
  # Minimal validation in offline mode
  validate_keys_on_startup: false
  timeout: 5.0
  max_retries: 1

# Audio System Configuration
audio:
  # Offline-optimized audio settings
  vad_enabled: true
  silence_threshold: 0.001
  silence_duration: 1.0
  min_audio_length: 0.3
  max_audio_length: 30.0
  
  # Enable audio processing for better offline experience
  noise_reduction: true
  echo_cancellation: true
  automatic_gain_control: true

# Speech-to-Text Configuration
stt:
  # Offline STT settings - prioritize local models
  primary_provider: "whisper-cpp"
  primary_model: "tiny.en"
  primary_language: "en"
  
  # Fallback to smaller local model
  fallback_provider: "whisper-cpp"
  fallback_model: "base.en"
  
  # Faster timeouts for offline
  timeout: 5.0
  temperature: 0.0
  max_retries: 1

# Text-to-Speech Configuration
tts:
  # Offline TTS settings - prioritize local models
  primary_provider: "piper"
  primary_model: "en_US-lessac-medium"
  primary_voice: "en_US-lessac-medium"
  primary_speed: 1.0
  
  # Fallback to faster local model
  fallback_provider: "piper"
  fallback_voice: "en_US-lessac-low"
  
  # Offline timeouts
  timeout: 10.0
  response_format: "wav"
  max_retries: 1
  
  # Lower quality for offline
  quality: "standard"
  enable_ssml: false

# Language Model Configuration
llm:
  # Offline-optimized models - prioritize local
  fast:
    provider: "llama-cpp"
    model: "gemma-2b-it-q4_0.gguf"
    max_tokens: 200
    temperature: 0.7
    timeout: 5.0
    cost_per_1k_tokens: 0.0
    max_requests_per_minute: 1000
    context_window: 2048
  
  deep:
    provider: "llama-cpp"
    model: "gemma-7b-it-q4_0.gguf"
    max_tokens: 500
    temperature: 0.7
    timeout: 15.0
    cost_per_1k_tokens: 0.0
    max_requests_per_minute: 1000
    context_window: 4096
  
  local:
    provider: "llama-cpp"
    model: "gemma-2b-it-q4_0.gguf"
    max_tokens: 200
    temperature: 0.7
    timeout: 5.0
    cost_per_1k_tokens: 0.0
    max_requests_per_minute: 1000
    context_window: 2048
  
  # Offline fallback chain - all local
  enable_fallback: true
  fallback_chain: ["fast", "deep", "local"]
  max_fallback_attempts: 2

# Memory System Configuration
memory:
  # Offline memory settings
  provider: "chroma"
  persist_directory: "./data/chroma"
  collection_name_conversations: "sovereign_conversations_offline"
  collection_name_screen: "sovereign_screen_offline"
  
  # Local embeddings (if available)
  embedding_provider: "sentence-transformers"
  embedding_model: "all-MiniLM-L6-v2"
  embedding_batch_size: 50
  
  # Offline retrieval
  retrieval_k: 3
  similarity_threshold: 0.6
  max_context_length: 4000
  
  # Offline memory management
  max_conversations_per_session: 50
  cleanup_interval_hours: 48
  enable_memory_compression: false

# Screen Monitoring Configuration
screen:
  enabled: true
  screenshot_interval: 5.0  # Less frequent for offline
  
  # Offline OCR settings
  ocr_provider: "tesseract"
  ocr_language: "eng"
  ocr_config: "--psm 6"
  tesseract_path: null
  
  # Offline image preprocessing
  resize_factor: 0.6  # Smaller for performance
  contrast_enhancement: true
  noise_reduction: true
  
  # Offline performance
  max_screen_history: 20
  enable_ocr_cache: true

# Code Agent Configuration
code_agent:
  enabled: false  # Disabled in offline mode
  provider: "local"
  model: "none"
  
  # Minimal settings for offline
  trigger_patterns: []
  max_tokens: 0
  temperature: 0.0
  timeout: 0.0
  max_context_files: 0
  max_context_size: 0

# Security Configuration
security:
  # Relaxed security for offline
  validate_api_keys: false
  mask_keys_in_logs: true
  
  # Offline encryption
  encrypt_memory: false
  encryption_key_file: null
  
  # Offline network security
  require_https: false
  allowed_hosts:
    - "localhost"
    - "127.0.0.1"
  
  # Offline rate limiting
  enable_rate_limiting: false
  max_requests_per_minute: 1000
  
  # Offline logging security
  log_user_input: true
  log_assistant_responses: true
  sanitize_logs: false

# Performance Monitoring Configuration
monitoring:
  enabled: true
  log_level: "INFO"
  log_file: "./logs/sovereign-offline.log"
  
  # Offline metrics
  metrics_enabled: true
  metrics_port: 8080
  
  # Offline health checks
  health_check_interval: 60.0
  health_check_timeout: 5.0
  
  # Offline performance tracking
  track_latency: true
  track_memory_usage: true
  track_cpu_usage: true
  
  # Offline error tracking
  error_reporting: true
  max_error_backlog: 100

# Development Configuration
development:
  debug_mode: false
  test_mode: false
  mock_apis: true  # Use mocks in offline mode
  
  # Hot reload for offline development
  enable_hot_reload: true
  hot_reload_paths:
    - "config/"
    - "assistant/"
  
  # Offline development shortcuts
  skip_audio_init: false
  use_test_data: false
  bypass_api_validation: true  # Bypass in offline mode 